apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias

      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
           name: db-configmap